package com.pvc.foodie.feature.audit.entity;

public enum AuditAction {
    USER_BLOCKED,
    USER_UNBLOCKED,
    RESTAURANT_OWNER_CREATED,
    DELIVERY_PARTNER_CREATED,
    USER_UPDATED,
    ORDER_STATUS_CHANGED,
    ORDER_PAYMENT_STATUS_CHANGED,
    ORDER_DELIVERY_PARTNER_CHANGED,
    RESTAURANT_CREATED,
    RESTAURANT_UPDATED,
    RESTAURANT_APPROVED,
    RESTAURANT_SUSPENDED,
    RESTAURANT_UNSUSPENDED,
    RESTAURANT_RAZORPAY_ACCOUNT_UPDATED,
    COUPON_CREATED,
    COUPON_UPDATED,
    COUPON_ACTIVATED,
    COUPON_DEACTIVATED,
    COUPON_DELETED,
    MENU_ITEM_UPDATED,
    MENU_ITEM_ENABLED,
    MENU_ITEM_DISABLED,
    MENU_ITEMS_BULK_UPLOADED
}
