services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: foodie-api

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}

      DB_URL: jdbc:postgresql://dpg-d8uvfcmrnols73foggdg-a.virginia-postgres.render.com:5432/foodie_e4bs
      DB_USER: foodie
      DB_PASSWORD: q6HvuYMb7dXuYGY8PcXzPh5GFBN4zJAJ

      JWT_SECRET: ${JWT_SECRET}
      APP_ADMIN_ENABLED: ${APP_ADMIN_ENABLED}
      APP_ADMIN_EMAIL: ${APP_ADMIN_EMAIL}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}

      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      APP_RESTAURANT_SIGNUP_ENABLED: ${APP_RESTAURANT_SIGNUP_ENABLED}
      APP_DELIVERY_PARTNER_SIGNUP_ENABLED: ${APP_DELIVERY_PARTNER_SIGNUP_ENABLED}
      APP_GUEST_CHECKOUT_OTP_DEBUG_RESPONSE_ENABLED: ${APP_GUEST_CHECKOUT_OTP_DEBUG_RESPONSE_ENABLED}
      APP_RATE_LIMIT_ENABLED: ${APP_RATE_LIMIT_ENABLED}

      RAZORPAY_ENABLED: ${RAZORPAY_ENABLED}
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}

      FIREBASE_ENABLED: ${FIREBASE_ENABLED}

      APP_DOCS_PUBLIC_ENABLED: "false"
      SPRINGDOC_API_DOCS_ENABLED: "false"
      SPRINGDOC_SWAGGER_UI_ENABLED: "false"

    ports:
      - "${APP_PORT:-8080}:8080"

    restart: unless-stopped
